#!/bin/bash
#SBATCH --time 01:00:00
#SBATCH --mem=24G
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --job-name big_boy_cyberner
#SBATCH --output cyberner.log

echo "loading conda"
module load Anaconda3
echo "init"
source ~/.bashrc
echo "acticate"
conda activate desktops

echo "loaded conda"
echo "loading new deps"
echo "loaded new deps"
echo "running train"
python nlp_cyber_ner/config.py
python nlp_cyber_ner/modeling/big_boy_train.py
echo "hello"
